# Generated by Django 4.1.7 on 2023-02-20 12:25

import baham.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('model_id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('vendor', models.CharField(max_length=20)),
                ('model', models.CharField(default='Unknown', max_length=20)),
                ('type', models.CharField(choices=[('AUTO_RICKSHAW', 'Auto Rickshaw'), ('SEDAN', 'Sedan'), ('HATCHBACK', 'Hatch Back'), ('SUV', 'Sub-Urban Vehicle'), ('VAN', 'Van'), ('HIGH_ROOF', 'High Roof'), ('MOTORCYCLE', 'Motor cycle/Scooter')], help_text='Select the vehicle chassis type', max_length=50)),
                ('capacity', models.PositiveSmallIntegerField(default=2)),
            ],
            options={
                'db_table': 'baham_vehicle_model',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('registration_number', models.CharField(help_text='Unique registration/license plate no. of the vehicle.', max_length=10, unique=True)),
                ('colour', models.CharField(default='white', max_length=50, validators=[baham.models.validate_colour])),
                ('date_added', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('FULL', 'Full'), ('INACTIVE', 'Inactive'), ('REMOVED', 'Removed')], max_length=50)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baham.vehiclemodel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
