# Generated by Django 4.1.7 on 2023-02-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baham', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='picture1',
            field=models.ImageField(null=True, upload_to='pictures'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='picture2',
            field=models.ImageField(null=True, upload_to='pictures'),
        ),
    ]
